mfile.o: mfile.cpp mgui.h profile_bin.h
mgui.o: mgui.cpp mgui.h profile_bin.h mv.h
mvAdaptiveFilter.o: mvAdaptiveFilter.cpp mv.h mgui.h profile_bin.h
mvClustering.o: mvClustering.cpp mvLines.h profile_bin.h mgui.h
mv.o: mv.cpp mv.h mgui.h profile_bin.h
mvHSVFilter.o: mvHSVFilter.cpp mv.h mgui.h profile_bin.h
mvLines.o: mvLines.cpp mvLines.h profile_bin.h mgui.h
mvScratchImage.o: mvScratchImage.cpp mv.h mgui.h profile_bin.h
mvShapes.o: mvShapes.cpp mvShapes.h mgui.h profile_bin.h mvLines.h mv.h
